services:
  mariadb:
    mem_limit: 256m
    image: mariadb:10.6
    container_name: mariadb-10.6-diet
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      MYSQL_ROOT_PASSWORD: mydatabasepassword
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
