services:
  postgres:
    image: postgres:16-bookworm
    container_name: postgresql-16-diet
    restart: unless-stopped

    ports:
      - "127.0.0.1:5432:5432"

    environment:
      POSTGRES_DB: mydatabasename
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword
      TZ: Asia/Jakarta

    volumes:
      - ./data:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro

    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf

    deploy:
      resources:
        limits:
          memory: 256M
